
export const QUESTION1_FAILURE = 'QUESTION1_FAILURE';
export const QUESTION1_SUCCESS = 'QUESTION1_SUCCESS';
export const QUESTION2_FAILURE = 'QUESTION2_FAILURE';
export const QUESTION2_SUCCESS = 'QUESTION2_SUCCESS';
export const QUESTION3_FAILURE = 'QUESTION3_FAILURE';
export const QUESTION3_SUCCESS = 'QUESTION3_SUCCESS';
